name: Verify Signed-off-by

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify_signed_off_commits:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Verify Signed-off-by trailer
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            git fetch origin ${{ github.base_ref }} --depth=1
            COMMITS=$(git rev-list origin/${{ github.base_ref }}..HEAD)
          else
            COMMITS=$(git rev-list ${{ github.event.before }}..${{ github.sha }})
          fi
          for COMMIT in $COMMITS; do
            echo "Checking commit $COMMIT"
            if ! git log -1 --pretty=%B "$COMMIT" | grep -q "^Signed-off-by:"; then
              echo "ERROR: commit $COMMIT is missing Signed-off-by trailer."
              exit 1
            fi
          done
          echo "All commits contain Signed-off-by trailer."
